services:
  db:
    image: mysql:9.4.0@sha256:91447968e66961302339ec4dc4d385f5e1a957d98e63c7d52ecf8b1de0907346
    container_name: mysql_db
    hostname: db
    restart: always
    env_file:
    - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  backend:
    container_name: backend
    build:
      context: backend
    ports:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
  
  frontend:
    container_name: frontend
    build:
      context: frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

volumes:
  mysql-data:
